/**
 * Dense screenshot pack — layered on top of seed-enrichment.
 */
import type {
  Bill,
  GuestCharge,
  GuestDeposit,
  Message,
  ServiceOrder,
  Task,
} from "@/lib/types";
import {
  DEMO_CLEANER_ID,
  DEMO_DEPOSIT_ID,
  DEMO_EMPLOYEE_ID,
  DEMO_GUEST_ID,
  DEMO_ORG_ID,
  DEMO_OWNER_ID,
  DEMO_STAY_ID,
  VILLA_IDS,
  demoPropertyPhoto,
} from "./seed-data";
import {
  DEPOSIT_CORAL,
  DEPOSIT_PALM,
  STAY_CORAL_ACTIVE,
  STAY_PALM_DONE,
} from "./seed-enrichment";

function daysFromNow(n: number) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

function daysAgo(n: number) {
  return daysFromNow(-n);
}

const CONTACT_NOK = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1";
const CONTACT_AC = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb7";

export const ORDER_LINEN = "77777777-7777-4777-8777-7777777777b1";
export const ORDER_PEST = "77777777-7777-4777-8777-7777777777b2";
export const ORDER_WINDOW = "77777777-7777-4777-8777-7777777777b3";
export const ORDER_HANDY = "77777777-7777-4777-8777-7777777777b4";
export const ORDER_DEEP = "77777777-7777-4777-8777-7777777777b5";
export const DEPOSIT_LOTUS_HELD = "77777777-7777-4777-8777-7777777777b6";
export const DEPOSIT_REEF = "77777777-7777-4777-8777-7777777777b7";

export const denseTasks: Task[] = [
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb1",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.lotus,
    title: "Top up drinking water (4 bottles)",
    priority: "normal",
    assigned_to: DEMO_CLEANER_ID,
    status: "done",
    due_date: daysAgo(0),
    time_start: "08:00",
    time_end: "08:20",
    created_by: DEMO_EMPLOYEE_ID,
    created_at: daysAgo(1) + "T18:00:00.000Z",
    completed_at: daysAgo(0) + "T08:18:00.000Z",
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb2",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.palm,
    title: "Change pool towels after shock",
    priority: "normal",
    assigned_to: DEMO_CLEANER_ID,
    status: "done",
    due_date: daysAgo(0),
    time_start: "16:15",
    time_end: "16:35",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(0) + "T12:00:00.000Z",
    completed_at: daysAgo(0) + "T16:30:00.000Z",
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb3",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.bamboo,
    title: "Steam clean mattress protectors",
    priority: "urgent",
    assigned_to: DEMO_CLEANER_ID,
    status: "open",
    due_date: daysFromNow(0),
    time_start: "14:00",
    time_end: "15:00",
    created_by: DEMO_EMPLOYEE_ID,
    created_at: daysAgo(0) + "T07:00:00.000Z",
    completed_at: null,
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: ORDER_LINEN,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb4",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.jungle,
    title: "Pest spray kitchen + bins",
    priority: "normal",
    assigned_to: DEMO_EMPLOYEE_ID,
    status: "open",
    due_date: daysFromNow(1),
    time_start: "09:30",
    time_end: "10:30",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(0) + "T09:00:00.000Z",
    completed_at: null,
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: ORDER_PEST,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb5",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.sunset,
    title: "Window wash ocean side",
    priority: "normal",
    assigned_to: DEMO_CLEANER_ID,
    status: "open",
    due_date: daysFromNow(2),
    time_start: "10:00",
    time_end: "12:00",
    created_by: DEMO_EMPLOYEE_ID,
    created_at: daysAgo(1) + "T11:00:00.000Z",
    completed_at: null,
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: ORDER_WINDOW,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb6",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.coral,
    title: "Fix sticking bathroom door",
    priority: "urgent",
    assigned_to: DEMO_EMPLOYEE_ID,
    status: "open",
    due_date: daysFromNow(0),
    time_start: "11:00",
    time_end: "11:45",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(0) + "T07:30:00.000Z",
    completed_at: null,
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: ORDER_HANDY,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb7",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.tide,
    title: "Deep clean before personal guest",
    priority: "urgent",
    assigned_to: DEMO_CLEANER_ID,
    status: "open",
    due_date: daysFromNow(1),
    time_start: "09:00",
    time_end: "13:00",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(0) + "T08:00:00.000Z",
    completed_at: null,
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: ORDER_DEEP,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb8",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.reef,
    title: "Restock coffee + sugar",
    priority: "normal",
    assigned_to: DEMO_CLEANER_ID,
    status: "done",
    due_date: daysAgo(1),
    time_start: "15:00",
    time_end: "15:20",
    created_by: DEMO_EMPLOYEE_ID,
    created_at: daysAgo(2) + "T10:00:00.000Z",
    completed_at: daysAgo(1) + "T15:15:00.000Z",
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb9",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.lotus,
    title: "Check Wi-Fi router reboot",
    priority: "normal",
    assigned_to: DEMO_EMPLOYEE_ID,
    status: "done",
    due_date: daysAgo(2),
    time_start: "17:00",
    time_end: "17:20",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(3) + "T12:00:00.000Z",
    completed_at: daysAgo(2) + "T17:10:00.000Z",
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccba",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.palm,
    title: "Photograph pool chemistry strip",
    priority: "normal",
    assigned_to: DEMO_CLEANER_ID,
    status: "done",
    due_date: daysAgo(0),
    time_start: "15:40",
    time_end: "15:50",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(0) + "T14:00:00.000Z",
    completed_at: daysAgo(0) + "T15:45:00.000Z",
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccbb",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.sunset,
    title: "Buy mosquito coils for guest",
    priority: "normal",
    assigned_to: DEMO_EMPLOYEE_ID,
    status: "done",
    due_date: daysAgo(3),
    time_start: null,
    time_end: null,
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(4) + "T09:00:00.000Z",
    completed_at: daysAgo(3) + "T11:00:00.000Z",
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccbc",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.office,
    title: "Show office to walk-in at 16:00",
    priority: "normal",
    assigned_to: DEMO_EMPLOYEE_ID,
    status: "open",
    due_date: daysFromNow(0),
    time_start: "16:00",
    time_end: "16:30",
    created_by: DEMO_OWNER_ID,
    created_at: daysAgo(0) + "T10:00:00.000Z",
    completed_at: null,
    notes: null,
    verify_notes: null,
    verify_photo_url: null,
    verify_submitted_by: null,
    verify_submitted_at: null,
    service_order_id: null,
  },
];

export const denseServiceOrders: ServiceOrder[] = [
  {
    id: ORDER_LINEN,
    org_id: DEMO_ORG_ID,
    contact_id: CONTACT_NOK,
    staff_profile_id: DEMO_CLEANER_ID,
    ordered_by: DEMO_EMPLOYEE_ID,
    villa_id: VILLA_IDS.bamboo,
    location_label: "Bamboo Nest",
    service_type: "Steam clean protectors",
    details: "All beds · dry thoroughly before remake.",
    scheduled_date: daysFromNow(0),
    time_start: "14:00",
    time_end: "15:00",
    status: "agreed",
    agreed_at: daysAgo(0) + "T07:20:00.000Z",
    chat_message_id: null,
    task_id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb3",
    created_at: daysAgo(0) + "T07:05:00.000Z",
  },
  {
    id: ORDER_PEST,
    org_id: DEMO_ORG_ID,
    contact_id: null,
    staff_profile_id: DEMO_EMPLOYEE_ID,
    ordered_by: DEMO_OWNER_ID,
    villa_id: VILLA_IDS.jungle,
    location_label: "Jungle Retreat",
    service_type: "Pest spray",
    details: "Kitchen + outdoor bins · guest away 09:30-10:30.",
    scheduled_date: daysFromNow(1),
    time_start: "09:30",
    time_end: "10:30",
    status: "pending_ack",
    agreed_at: null,
    chat_message_id: null,
    task_id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb4",
    created_at: daysAgo(0) + "T09:05:00.000Z",
  },
  {
    id: ORDER_WINDOW,
    org_id: DEMO_ORG_ID,
    contact_id: CONTACT_NOK,
    staff_profile_id: DEMO_CLEANER_ID,
    ordered_by: DEMO_EMPLOYEE_ID,
    villa_id: VILLA_IDS.sunset,
    location_label: "Sunset Deck",
    service_type: "Window wash",
    details: "Ocean-facing glass only · bring ladder.",
    scheduled_date: daysFromNow(2),
    time_start: "10:00",
    time_end: "12:00",
    status: "pending_ack",
    agreed_at: null,
    chat_message_id: null,
    task_id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb5",
    created_at: daysAgo(1) + "T11:10:00.000Z",
  },
  {
    id: ORDER_HANDY,
    org_id: DEMO_ORG_ID,
    contact_id: CONTACT_AC,
    staff_profile_id: DEMO_EMPLOYEE_ID,
    ordered_by: DEMO_OWNER_ID,
    villa_id: VILLA_IDS.coral,
    location_label: "Coral Bungalow",
    service_type: "Door plane + hinge oil",
    details: "Guest reported sticking bathroom door.",
    scheduled_date: daysFromNow(0),
    time_start: "11:00",
    time_end: "11:45",
    status: "agreed",
    agreed_at: daysAgo(0) + "T08:00:00.000Z",
    chat_message_id: null,
    task_id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb6",
    created_at: daysAgo(0) + "T07:35:00.000Z",
  },
  {
    id: ORDER_DEEP,
    org_id: DEMO_ORG_ID,
    contact_id: CONTACT_NOK,
    staff_profile_id: DEMO_CLEANER_ID,
    ordered_by: DEMO_OWNER_ID,
    villa_id: VILLA_IDS.tide,
    location_label: "Tide Studio",
    service_type: "Deep clean",
    details: "Personal booking tomorrow · full deep clean.",
    scheduled_date: daysFromNow(1),
    time_start: "09:00",
    time_end: "13:00",
    status: "agreed",
    agreed_at: daysAgo(0) + "T08:30:00.000Z",
    chat_message_id: null,
    task_id: "cccccccc-cccc-4ccc-8ccc-ccccccccccb7",
    created_at: daysAgo(0) + "T08:05:00.000Z",
  },
];

export const denseBills: Bill[] = [
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb1",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.bamboo,
    description: "Linen detergent + fabric softener",
    amount: 420,
    currency: "THB",
    status: "pending",
    category: "cleaning",
    due_date: daysFromNow(2),
    submitted_by: DEMO_CLEANER_ID,
    receipt_photo_url: null,
    created_at: daysAgo(0) + "T12:20:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb2",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.jungle,
    description: "Pest spray cans (3)",
    amount: 890,
    currency: "THB",
    status: "pending",
    category: "maintenance",
    due_date: daysFromNow(1),
    submitted_by: DEMO_EMPLOYEE_ID,
    receipt_photo_url: null,
    created_at: daysAgo(0) + "T09:40:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb3",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.sunset,
    description: "Window squeegee + microfiber pack",
    amount: 310,
    currency: "THB",
    status: "paid",
    category: "cleaning",
    due_date: daysAgo(1),
    submitted_by: DEMO_CLEANER_ID,
    receipt_photo_url: null,
    created_at: daysAgo(2) + "T15:00:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb4",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.coral,
    description: "Door hinge oil + sandpaper",
    amount: 180,
    currency: "THB",
    status: "pending",
    category: "maintenance",
    due_date: daysFromNow(0),
    submitted_by: DEMO_EMPLOYEE_ID,
    receipt_photo_url: null,
    created_at: daysAgo(0) + "T08:10:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb5",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.tide,
    description: "Deep-clean supplies restock",
    amount: 1450,
    currency: "THB",
    status: "pending",
    category: "cleaning",
    due_date: daysFromNow(3),
    submitted_by: DEMO_CLEANER_ID,
    receipt_photo_url: null,
    created_at: daysAgo(0) + "T11:00:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb6",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.lotus,
    description: "Water delivery (12 bottles)",
    amount: 360,
    currency: "THB",
    status: "paid",
    category: "utilities",
    due_date: daysAgo(0),
    submitted_by: DEMO_CLEANER_ID,
    receipt_photo_url: null,
    created_at: daysAgo(0) + "T08:25:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb7",
    org_id: DEMO_ORG_ID,
    villa_id: null,
    description: "Fuel · scooter for villa runs",
    amount: 500,
    currency: "THB",
    status: "paid",
    category: "transport",
    due_date: daysAgo(4),
    submitted_by: DEMO_EMPLOYEE_ID,
    receipt_photo_url: null,
    created_at: daysAgo(4) + "T19:00:00.000Z",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-ddddddddddb8",
    org_id: DEMO_ORG_ID,
    villa_id: VILLA_IDS.palm,
    description: "Pool shock tablets (box)",
    amount: 2200,
    currency: "THB",
    status: "pending",
    category: "pool",
    due_date: daysFromNow(4),
    submitted_by: DEMO_CLEANER_ID,
    receipt_photo_url: null,
    created_at: daysAgo(1) + "T16:30:00.000Z",
  },
];

export const denseMessages: Message[] = [
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb1",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_OWNER_ID,
    body: "Can someone confirm Bamboo Nest keys are back on the board?",
    created_at: daysAgo(0) + "T07:50:00.000Z",
    service_order_id: null,
    channel: "request",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb2",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_CLEANER_ID,
    body: "Keys back · board hook #4. Linen bag left at the gate.",
    created_at: daysAgo(0) + "T08:05:00.000Z",
    service_order_id: null,
    channel: "request",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb3",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_EMPLOYEE_ID,
    body: "Feedback: guest at Coral loved the welcome fruit — keep doing that.",
    created_at: daysAgo(0) + "T09:20:00.000Z",
    service_order_id: null,
    channel: "request",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb4",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_OWNER_ID,
    body: "Please check this sink photo — is this the same leak as morning?",
    created_at: daysAgo(0) + "T10:05:00.000Z",
    service_order_id: null,
    channel: "photo",
    attachment_url: demoPropertyPhoto("sunset"),
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb5",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_EMPLOYEE_ID,
    body: "Same cabinet · trap loose. Tightening now, will send after photo.",
    created_at: daysAgo(0) + "T10:18:00.000Z",
    service_order_id: null,
    channel: "photo",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb6",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_CLEANER_ID,
    body: "Pool strip after shock — chlorine looks good.",
    created_at: daysAgo(0) + "T15:48:00.000Z",
    service_order_id: null,
    channel: "photo",
    attachment_url: demoPropertyPhoto("palm"),
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb7",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_OWNER_ID,
    body: "Anyone grabbing coffee in Thong Sala? I can cover if you bring two iced.",
    created_at: daysAgo(0) + "T08:40:00.000Z",
    service_order_id: null,
    channel: "general",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb8",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_CLEANER_ID,
    body: "On it — 20 mins. Rain starting near Srithanu.",
    created_at: daysAgo(0) + "T08:46:00.000Z",
    service_order_id: null,
    channel: "general",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeb9",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_EMPLOYEE_ID,
    body: "Weather looks clear by 14:00 for the AC tech at Jungle.",
    created_at: daysAgo(0) + "T09:05:00.000Z",
    service_order_id: null,
    channel: "general",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeeba",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_OWNER_ID,
    body: "Question: do we still have spare remote batteries in the office?",
    created_at: daysAgo(1) + "T16:40:00.000Z",
    service_order_id: null,
    channel: "request",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeebb",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_EMPLOYEE_ID,
    body: "Yes — bottom drawer left · 4 packs AA.",
    created_at: daysAgo(1) + "T16:55:00.000Z",
    service_order_id: null,
    channel: "request",
    attachment_url: null,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeebc",
    org_id: DEMO_ORG_ID,
    sender_id: DEMO_CLEANER_ID,
    body: "Proof: Bamboo Nest after linen change.",
    created_at: daysAgo(0) + "T13:40:00.000Z",
    service_order_id: null,
    channel: "photo",
    attachment_url: demoPropertyPhoto("bamboo"),
  },
];

export const denseGuestDeposits: GuestDeposit[] = [
  {
    id: DEPOSIT_LOTUS_HELD,
    org_id: DEMO_ORG_ID,
    stay_id: DEMO_STAY_ID,
    amount: 10000,
    currency: "THB",
    status: "held",
    refunded_amount: 0,
    notes: "Primary stay deposit · deductions logged separately.",
    deposit_timing: "on_arrival",
    created_at: daysAgo(5) + "T12:30:00.000Z",
  },
  {
    id: DEPOSIT_REEF,
    org_id: DEMO_ORG_ID,
    stay_id: STAY_CORAL_ACTIVE,
    amount: 3000,
    currency: "THB",
    status: "held",
    refunded_amount: 0,
    notes: "Extra key deposit · cash.",
    deposit_timing: "on_arrival",
    created_at: daysAgo(1) + "T14:10:00.000Z",
  },
];

export const denseGuestCharges: GuestCharge[] = [
  {
    id: "77777777-7777-4777-8777-7777777777c1",
    org_id: DEMO_ORG_ID,
    stay_id: DEMO_STAY_ID,
    deposit_id: DEMO_DEPOSIT_ID,
    description: "Stained duvet cover replacement",
    amount: 1200,
    currency: "THB",
    proof_photo_url: demoPropertyPhoto("lotus"),
    created_at: daysAgo(1) + "T18:00:00.000Z",
  },
  {
    id: "77777777-7777-4777-8777-7777777777c2",
    org_id: DEMO_ORG_ID,
    stay_id: DEMO_STAY_ID,
    deposit_id: DEMO_DEPOSIT_ID,
    description: "Missing beach towel (x2)",
    amount: 600,
    currency: "THB",
    proof_photo_url: null,
    created_at: daysAgo(0) + "T11:20:00.000Z",
  },
  {
    id: "77777777-7777-4777-8777-7777777777c3",
    org_id: DEMO_ORG_ID,
    stay_id: STAY_PALM_DONE,
    deposit_id: DEPOSIT_PALM,
    description: "Deep clean after party (extra hours)",
    amount: 2000,
    currency: "THB",
    proof_photo_url: demoPropertyPhoto("palm"),
    created_at: daysAgo(0) + "T12:00:00.000Z",
  },
  {
    id: "77777777-7777-4777-8777-7777777777c4",
    org_id: DEMO_ORG_ID,
    stay_id: STAY_CORAL_ACTIVE,
    deposit_id: DEPOSIT_CORAL,
    description: "Broken ceramic mug",
    amount: 150,
    currency: "THB",
    proof_photo_url: null,
    created_at: daysAgo(0) + "T19:00:00.000Z",
  },
];
